version: '3'

services:
  api:
    build: 
      context: ./backend
    container_name: api-backend
    volumes: 
      - .:/app
    restart: always
    ports:
      - 8080:8080

  web:
    build:
      context: ./web
    stdin_open: true
    volumes:
    - .:/app/project
    - .:/app/node_modules
    ports:
      - 3000:3000
      